<?php

namespace CtiDigital\Configurator\Model\Component;

use Magento\Catalog\Api\Data\ProductLinkInterfaceFactory;

class ProductLinks extends YamlComponentAbstract
{

    protected $alias = 'productlinks';
    protected $name = 'Product Links';
    protected $description = 'Component to create and maintain product links (related/up-sells/cross-sells)';

    public function canParseAndProcess()
    {
        return parent::canParseAndProcess(); // TODO: Change the autogenerated stub
    }

    public function processData($data = null)
    {
        // TODO: Implement processData() method.
    }


}